# Generated by Django 6.0.3 on 2026-03-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(choices=[('UNDC', 'Undecided'), ('CSEN', 'Computer Science and Engineering'), ('LAC', 'Liberal Arts'), ('BUSI', 'Business & Entrepreneurship'), ('ARTS', 'Fine Arts'), ('SCI', 'Science')], default='UNDC', max_length=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(choices=[('UNDC', 'Undecided'), ('CSCI', 'Computer Science'), ('ELA', 'English'), ('FINC', 'Finance'), ('ART', 'Art'), ('BIO', 'Biology')], default='UNDC', max_length=4),
        ),
    ]
