# Generated by Django 6.0.2 on 2026-04-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0003_feedchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupevent',
            name='description',
            field=models.TextField(blank=True, default='This is an event!'),
        ),
    ]
