# Generated by Django 4.2.30 on 2026-04-10 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0003_feedchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupevent',
            name='description',
            field=models.TextField(blank=True, default='This event is happening!'),
        ),
        migrations.AddField(
            model_name='profile',
            name='classes',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='college',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedchat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2026, 4, 16)),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='major',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
