# Generated by Django 4.2.30 on 2026-04-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0005_alter_college_id_alter_feedchat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='classification',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate'), ('PD', 'Doctoral')], default='FR', max_length=2),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='classes',
        ),
        migrations.AddField(
            model_name='profile',
            name='classes',
            field=models.ManyToManyField(blank=True, to='classApp.course'),
        ),
    ]
