# Generated by Django 4.2.30 on 2026-04-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0006_course_profile_classification_remove_profile_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='is_graduate',
            field=models.BooleanField(default=False),
        ),
    ]
