# Generated by Django 6.0.3 on 2026-04-15 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0007_major_is_graduate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupevent',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2026, 4, 21)),
        ),
    ]
