# Generated by Django 6.0.3 on 2026-04-16 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0008_alter_groupevent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupevent',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2026, 4, 23)),
        ),
    ]
