# Generated by Django 6.0.4 on 2026-04-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0009_alter_groupevent_date_grouppost'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedchat',
            name='resource_file',
            field=models.FileField(blank=True, null=True, upload_to='feed_resources/'),
        ),
        migrations.AddField(
            model_name='feedchat',
            name='resource_file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='feedchat',
            name='resource_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='resource_file',
            field=models.FileField(blank=True, null=True, upload_to='group_resources/'),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='resource_file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='resource_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
