# Generated by Django 6.0.4 on 2026-04-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0010_feedchat_resource_file_feedchat_resource_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedchat',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
