# Generated by Django 6.0.4 on 2026-05-14 01:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0011_alter_feedchat_content_alter_grouppost_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupevent',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveField(
            model_name='groupevent',
            name='date',
        ),
        migrations.AddField(
            model_name='groupevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupevent',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='google_event_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='classApp.studygroup'),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
