# Generated by Django 6.0.2 on 2026-04-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0004_groupevent_description'),
        ('classApp', '0011_alter_feedchat_content_alter_grouppost_content'),
    ]

    operations = [
    ]
