# Generated by Django 6.0.2 on 2026-04-28 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0012_merge_20260423_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupevent',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2026, 5, 5)),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='description',
            field=models.TextField(blank=True, default='This event is happening!'),
        ),
    ]
