# Generated by Django 6.0.4 on 2026-05-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0012_alter_groupevent_options_remove_groupevent_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupevent',
            options={'ordering': ['session_start_date', 'session_start_time']},
        ),
        migrations.RemoveField(
            model_name='groupevent',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='groupevent',
            name='start_time',
        ),
        migrations.AddField(
            model_name='groupevent',
            name='meeting_days',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='session_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='session_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='session_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='session_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
