# Generated by Django 4.2.30 on 2026-05-14 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0013_alter_groupevent_date_alter_groupevent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupevent',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2026, 5, 20)),
        ),
    ]
