# Generated by Django 4.2.30 on 2026-05-14 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0012_alter_groupevent_options_remove_groupevent_date_and_more'),
        ('classApp', '0014_alter_groupevent_date'),
    ]

    operations = [
    ]
