# Generated by Django 4.2.30 on 2026-05-14 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0013_alter_groupevent_options_remove_groupevent_end_time_and_more'),
        ('classApp', '0015_merge_20260513_2113'),
    ]

    operations = [
    ]
