# Generated by Django 4.2.30 on 2026-05-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0016_merge_20260513_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupevent',
            name='session_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]